In [2]:
import imutils
import cv2

In [2]:
image=cv2.imread('jp.png')

In [3]:
# load the input image and show its dimensions, keeping in mind that
# images are represented as a multi-dimensional NumPy array with
# shape no. rows (height) x no. columns (width) x no. channels (depth)
(h, w, d) = image.shape
print("width={}, height={}, depth={}".format(w, h, d))

width=600, height=322, depth=3


In [4]:
# access the RGB pixel located at x=50, y=100, keepind in mind that
# OpenCV stores images in BGR order rather than RGB
(B, G, R) = image[100, 50]
print("R={}, G={}, B={}".format(R, G, B))

R=41, G=49, B=37


In [7]:
# extract a 100x100 pixel square ROI (Region of Interest) from the
# input image starting at x=320,y=60 at ending at x=420,y=160
roi = image[60:160,320:420]
cv2.imshow('ROI',roi)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
# resize the image to 200x200px, ignoring aspect ratio
resize = cv2.resize(image,(200,200))
cv2.imshow('ROI',resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
# fixed resizing and distort aspect ratio so let's resize the width
# to be 300px but compute the new height based on the aspect ratio
r = 300.0 / w
dim = (300, int(h * r))
resized = cv2.resize(image, dim)
cv2.imshow("Aspect Ratio Resize", resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
print(dim)

(300, 161)


In [9]:
# manually computing the aspect ratio can be a pain so let's use the
# imutils library instead
resized = imutils.resize(image, width=400)
cv2.imshow("Imutils Resize", resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
# let's rotate an image 45 degrees clockwise using OpenCV by first
# computing the image center, then constructing the rotation matrix,
# and then finally applying the affine warp
center = (w // 2, h // 2)
M = cv2.getRotationMatrix2D(center, -45, 1.0)
rotated = cv2.warpAffine(image, M, (w, h))
cv2.imshow("OpenCV Rotation", rotated)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
# rotation can also be easily accomplished via imutils with less code
rotated = imutils.rotate(image, -30)
cv2.imshow("Imutils Rotation", rotated)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
# OpenCV doesn't "care" if our rotated image is clipped after rotation
# so we can instead use another imutils convenience function to help us out
rotated = imutils.rotate_bound(image, 45)
cv2.imshow("Imutils Bound Rotation", rotated)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
# apply a Gaussian blur with a 11x11 kernel to the image to smooth it,
# useful when reducing high frequency noise
blurred = cv2.GaussianBlur(image, (11, 11), 0)
cv2.imshow("Blurred", blurred)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
# draw a 2px thick red rectangle surrounding the face
op = image.copy()
cv2.rectangle(op,(320,60),(420,160),(0,255,0),3) #Start (Top Left pixel) (x,y), End (Bottom Right pixel) (x,y)
cv2.imshow("Rectangle", op)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
# draw a blue 20px (filled in) circle on the image centered at
# x=300,y=150
output = image.copy()
cv2.circle(output, (300, 150), 20, (255, 255, 255), -1)
cv2.imshow("Circle", output)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
# draw a 5px thick red line from x=60,y=20 to x=400,y=200
output = image.copy()
cv2.line(output, (60, 20), (400, 200), (0, 0, 255), 5)
cv2.imshow("Line", output)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
# draw green text on the image
output = image.copy()
cv2.putText(output,"OpenCV + Jurassic Park..!",(10,25),
            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
cv2.imshow("Message",output)
cv2.waitKey(0)


In [3]:
#Tetris blocks
image = cv2.imread('tetris_blocks.png')
cv2.imshow("Image", image)
cv2.waitKey(0)
 
# convert the image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("Gray", gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
# applying edge detection we can find the outlines of objects in images
edged = cv2.Canny(gray,30,150)
cv2.imshow("Canny Edged", edged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
# threshold the image by setting all pixel values less than 225
# to 255 (white; foreground) and all pixel values >= 225 to 0
# (black; background), thereby segmenting the image
thresh = cv2.threshold(gray,225,255,cv2.THRESH_BINARY_INV)[1]
cv2.imshow("Threshold", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
# find contours (i.e., outlines) of the foreground objects in the thresholded image
cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL,
cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
output = image.copy()
# loop over the contours
for c in cnts:
    # draw each contour on the output image with a 3px thick purple
    # outline, then display the output contours one at a time
    cv2.drawContours(output, [c], -1, (240, 0, 159), 3)
    cv2.imshow("Contours", output)
    cv2.waitKey(0)

cv2.destroyAllWindows()

In [7]:
# draw the total number of contours found in purple
text = "I found {} objects".format(len(cnts))
cv2.putText(output,text,(10,25),
             cv2.FONT_HERSHEY_SIMPLEX, 0.7,(200,140,76),2)
cv2.imshow("Number of objects", output)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
# we apply erosions to reduce the size of foreground objects
mask = thresh.copy()
mask = cv2.erode(mask, None, iterations=5)
cv2.imshow("Eroded", mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [43]:
# similarly, dilations can increase the size of the ground objects
mask = thresh.copy()
mask = cv2.dilate(mask, None, iterations=5)
cv2.imshow("Dilated", mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [51]:
# a typical operation we may want to apply is to take our mask and
# apply a bitwise AND to our input image, keeping only the masked
# regions
mask = thresh.copy()
cv2.imshow("Mask", mask)
cv2.waitKey(0)
cv2.imshow("Image", image)
cv2.waitKey(0)
output = cv2.bitwise_and(image, image, mask=mask)
cv2.imshow("Mask", output)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
#Full code.
import cv2
import numpy as np
import imutils
# Counting shapes(objects) mini project
image = cv2.imread('tetris_blocks.png')
cv2.imshow("Image", image)
cv2.waitKey(0)
cv2.waitKey(0)
 
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("Gray", gray)
cv2.waitKey(0)

canny = cv2.Canny(gray,30,150)
cv2.imshow("Canny", canny)
cv2.waitKey(0)

thresh = cv2.threshold(gray,225,255,cv2.THRESH_BINARY_INV)[1]
cv2.imshow("Threshold", thresh)
cv2.waitKey(0)

cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL,
cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
#cnts will store 4 points(x,y) of the shape.
cnts = sorted(cnts, key = cv2.contourArea, reverse = True)[:6]
print('Contours' + str(cnts[0]))
output = image.copy()
# loop over the contours
for c in cnts:
    cv2.drawContours(output, [c], -1, (240, 0, 159), 3)
    cv2.imshow("Contours", output)
    cv2.waitKey(0)

cv2.destroyAllWindows()
text = "I found {} objects".format(len(cnts))
cv2.putText(output,text,(10,25),
             cv2.FONT_HERSHEY_SIMPLEX, 0.7,(200,140,76),2)
cv2.imshow("Number of objects", output)
cv2.waitKey(0)
cv2.destroyAllWindows()

Contours[[[ 22  80]]

 [[ 22 112]]

 [[145 112]]

 [[145  80]]]
